/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: f32fe21595423fdb96a18e5af7d9134a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Chat";
	}
	interface Env {
		AI: Ai;
		ASSETS: Fetcher;
		Chat: DurableObjectNamespace<import("./src/index").Chat>;
	}
}
interface Env extends Cloudflare.Env {}
